project_id = "mzqwwmxqxpertvyefarp"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.process-email-queue]
    verify_jwt = true
  [functions.send-transactional-email]
    verify_jwt = false
  [functions.preview-transactional-email]
    verify_jwt = false
  [functions.handle-email-unsubscribe]
    verify_jwt = false
  [functions.handle-email-suppression]
    verify_jwt = false
  [functions.paytr-callback]
    verify_jwt = false
  [functions.verify-paytr-payment]
    verify_jwt = true
  [functions.notify-admin-email]
    verify_jwt = false
  [functions.gmail-inbox]
    verify_jwt = true
