project_id = "ntczttevbqmnkinvertq"

[functions.send-notification]
verify_jwt = false

[functions.verify-ruhsat]
verify_jwt = false

[functions.phone-otp]
verify_jwt = false

[functions.admin-panel]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.create-paytr-token]
verify_jwt = false

[functions.paytr-callback]
verify_jwt = false

[functions.initiate-call]
verify_jwt = false

[functions.delete-account]
verify_jwt = false

[functions.support-chat]
verify_jwt = false
